### ISSUE TITLE
Update locations manually now that sheet is updated

### ISSUE THREAD

**Issue by vsoch** [USRSE/usrse-map#18]

**Comment by tcooper** [comment]
Without permissions to view the Google Doc I cannot be certain but I registered last Thursday (2020-04-09) which was before you committed the change (Saturday) that prevented the map update yesterday (Sunday). I definitely used a location that is not checked in so it would (should?) have generated a map update yesterday if everything is working correctly in the automation.

**Comment by vsoch** [comment]
Thanks for letting me know! It could be that the Google Sheet has changed in format / something else, and I'm not aware of it. I'll look into this tomorrow for you!

**Comment by vsoch** [comment]
okay figured it out - the sheet was not updating for the range needed (the locations are on a separate sheet from the raw data to protect people's names, personal information, etc). I just fixed the sheet, and I should be able to give it a run locally tomorrow to update! I suspect we will have quite a few new locations. Thanks for pinging me!

**Comment by tcooper** [comment]
Hmm... when tomorrow becomes today I wonder if you're getting out enough... although I'm pretty sure you've been doing the remote thing for long enough to have the time management challenge licked. Is it more a _can't leave puzzle unsolved_ problem?

**Comment by vsoch** [comment]
Yep, you got me pegged :) I can sleep okay knowing how something is (or isn't working) and that I can fix it promptly the next day, otherwise I am very likely to wake up and seek out that information. I also am (blessed? cursed?) with the opposite of procrastination, an urgency to do things as quickly as I can. It's not really balanced like most people would define, but figuring out little challenges / puzzles, whether it's something silly like this or something more complex, is what gives me meaning. So I do a lot of things like that. :)

**Comment by vsoch** [comment]
Quick update - so many new locations!
```
stanford university, slac	Stanford, CA
university of arizona	
university of colorado, boulder
slac
california institute of technology
stanford health care
university of wisconsin-madison
cuny hunter college
caltech/ipac
stanford university school of medicine
nasa exoplanet science institute / ipac-caltech
university of colorado at boulder
slac/stanford
mcgill university, montreal neurological institute
us naval research laboratory
lbl
cohere consulting, llc
columbia university and self
university of dundee
university of wisconsinâmadison
san diego supercomputer center
university of new hampshire
lawrence berkeley national lab
mcmaster university
slac national accelerator lab
university of hawaii
llnsâ¯llc
llnl
ncsa
university of illinois
boston university
uiuc.edu
```
Adding them to the lookup now.

**Comment by vsoch** [comment]
okay we're good! https://twitter.com/vsoch/status/1250156224626057218 Thanks @tcooper !
