### ISSUE TITLE
New Membership failed to populate location on map

### ISSUE THREAD

**Issue by jpummil** [USRSE/usrse-map#32]
Fayetteville, AR

Joined on Wednesday the 12th. Maybe a glitch in the automated map population process?

--Jeff Pummill - University of Arkansas

**Comment by vsoch** [comment]
It's only updated at the end of the month, so you would see this new entry early September. Does that make sense?

**Comment by jpummil** [comment]
Hey Vanessa!
Got it ;-) Sign up page just made it sound like it happened as part of the onboarding process I guess.
Thanks for the quick response!

**Comment by vsoch** [comment]
Sure thing! We can leave the issue open so I can ping you when it's updated if you like.

**Comment by vsoch** [comment]
hey @jpummil you are added! https://github.com/USRSE/usrse-map/pull/36/files#diff-cb779beb97782959b5f05be50add1c70R127. 
And there you are!

![image](https://user-images.githubusercontent.com/814322/91784742-d7809d80-ebc0-11ea-9e04-5154e2365122.png)

https://us-rse.org/usrse-map/

Thanks for joining us-rse! (:
